### ISSUE TITLE
/docs returns "Cannot read property 'readFile' of undefined"

### ISSUE THREAD

**Issue by brenc** [haproxytech/dataplaneapi#184]
Just set up the API yesterday to run alongside haproxy. First URL I tested when I got everything up and running was `/docs` which returns this strange error:
```
Something went wrong...
Cannot read property 'readFile' of undefined
Stack trace
Error: Cannot read property 'readFile' of undefined
    at t.BaseResolver.<anonymous> (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:13512)
    at Generator.next (<anonymous>)
    at https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:11844
    at new Promise (<anonymous>)
    at r (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:11589)
    at t.BaseResolver.loadExternalRef (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:13294)
    at t.BaseResolver.<anonymous> (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:14002)
    at Generator.next (<anonymous>)
    at https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:37:11844
    at new Promise (<anonymous>)

ReDoc Version: 2.0.0-rc.51
Commit: 60bf22e
```
Nothing is getting reported to the logs even with debug logging turned on.

I have access to the docs elsewhere but thought I'd report this error.

HAProxy Data Plane API v2.2.1 7fb8e05
HA-Proxy version 2.2.13-5f3eb59

**Comment by mjuraga** [comment]
This may be an issue with your dataplaneapi process accessing redoc standalone that is used in the `docs` endpoint.

**Comment by brenc** [comment]
Is there some additional configuration I need to do? I didn't see any mention of this anywhere.
